#!/bin/bash

export_dir()
{
  mkdir export-dir && cp *.svg export-dir/ && cd export-dir
}

already_done()
{
  echo "It seems as if you have already run this script ($0) before!"
  echo "Please remove the 'export-dir' directory and/or check whether you are in the correct place before running this script!"
  exit 100
}


export_dir || already_done


for SVG in *.svg;
  do
    PIXMAP=${SVG/.svg/}

    inkscape "$SVG" --export-png="$PIXMAP.png" --export-area-snap --export-area-page --export-dpi=90
  done


mkdir svg
mv *.svg svg/
mkdir png
cp *.png png/

# I prefer the icons to be named 'icon_size' instead of 'icon-size', but $VAR_SIZE would be another variable, while $VAR-size is not troublesome.
# That's why the png files have been copied/backed up. So that we can rename the files for this script and then merely delete them.
rename 's/_/-/g' *.png

# icotool does not support PNG compression in ico files!
# gimp does support this...
for PNG in *-512.png;
  do
    ICON=${PNG/-512.png/}
    
    icotool -c "$ICON-16.png" "$ICON-24.png" "$ICON-32.png" "$ICON-48.png" "$ICON-64.png" "$ICON-96.png" "$ICON-128.png" "$ICON-256.png" -o "$ICON.ico"
    png2icns "$ICON.icns" "$ICON-16.png" "$ICON-32.png" "$ICON-48.png" "$ICON-128.png" "$ICON-256.png" "$ICON-512.png"
  done

# The first word in the filename is the category, so it should be separated from the name itself, by a _
# Only the first '-' needs to be replaced
rename 's/-/_/' *.ico
rename 's/-/_/' *.icns

# Moving the files, so that it is not a mess
mkdir ico
mv *.ico ico/
mkdir icns
mv *.icns icns/
rm -rf *.png

echo "Done. The resulting files can be found in the 'export-dir' folder"

exit 0
