#!/bin/bash
# Sometimes, we need to change the same things in loads of SVG files.
# No big deal, and next time, if needed, it won't be the same strings.
# But it's the first time I use sed so I'll keep this file in order to remember.
# Even though the syntax is quite common. Just in case.

# Well, is there a more elegant way?
for SVG in *.svg;
  do
    for COLOR in blue gnome grey orange purple white;
      do
        sed -i".old" -e "s/front-$COLOR-base-gradient/front-$COLOR-gradient/g" $SVG
        sed -i".old" -e "s/back-$COLOR-base-gradient/back-$COLOR-gradient/g" $SVG
        sed -i".old" -e "s/front-$COLOR-base-contour-gradient/front-contour-$COLOR-gradient/g" $SVG
        sed -i".old" -e "s/back-$COLOR-base-contour-gradient/back-contour-$COLOR-gradient/g" $SVG
      done
  done

# The 'sed' command creates a backup, but it is quite a mess.
# Make sure there is no .old file before running this script!
# Or at least, make sure you don't mind if these files are moved.
mkdir backup
mv *.old backup/

exit 0
